### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Phoebe-Macdonald** [openskynetwork/opensky-api#26]
I have successfully installed opensky-api
When running `pip install -e python` in my terminal I get: `Successfully installed opensky-api`)
However, if I then run 
```from opensky_api install OpenSkyAPI```
 I run into the following error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'opensky_api'

Is there an issue? Am I doing something  wrong?

**Comment by SLKTH** [comment]
I have the same issue.

**Comment by Forastierii** [comment]
Hey @Phoebe-Macdonald hoebe, did you manage to solve this issue?
I have the same problem.

**Comment by mouhsineelachbi** [comment]
Hi
The correct way to install opensky packages using pip and according to [#issue-634885026](https://github.com/openskynetwork/opensky-api/issues/27#issue-634885026)
pip install -e "git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python"

**Comment by Ruagit** [comment]
Hi @Phoebe-Macdonald did you ever resolve this issue? I am currently having this problem as well.

**Comment by micheleberardi** [comment]
@Ruagit this works for me 
`pip install -e "git+https://github.com/openskynetwork/opensky-api.git#egg=opensky-api&subdirectory=python"`

**Comment by CaMo111** [comment]
![problem](https://github.com/openskynetwork/opensky-api/assets/109951019/4ebc0097-6f8a-4a4d-b64d-22be17a92a41)

When i do what @mouhsineelachbi suggests, i get this error. Does anyone know how to resolve this?

**Comment by adriens** [comment]
With : 

```sh
pip install -e "git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python"
```
I got this error: 

```Obtaining python from git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python
  Updating ./src/python clone
  Running command git fetch -q --tags
  Running command git reset --hard -q c6f34a5a9e6dc37ce58852ffa9110f79c2980a80
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package python produced metadata for project name opensky-api. Fix your #egg=python fragments.
Discarding [git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python](git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python</span>): Requested opensky-api from git+https://github.com/openskynetwork/opensky-api.git#egg=python&subdirectory=python has inconsistent name: expected 'python', but metadata has 'opensky-api'
ERROR: Could not find a version that satisfies the requirement python (unavailable) (from versions: none)
ERROR: No matching distribution found for python (unavailable)
```

**Comment by adriens** [comment]
Did anyone manage to make it run recently?

**Comment by AWSBarker** [comment]
this is still not working.

**Comment by ahmetqunay** [comment]
git clone https://github.com/openskynetwork/opensky-api
cd opensky-api
pip install .

**Comment by praxii-debug** [comment]
git clone https://github.com/openskynetwork/opensky-api
cd opensky-api
cd python/
python3 setup.py build
python3 setup.py install

This worked for me

**Comment by jaluebbe** [comment]
I updated the pyproject.toml which is replacing the setup.py . Now, the installtion should work  via 
`pip install "git+https://github.com/openskynetwork/opensky-api.git#subdirectory=python"`
or as described via cloning the repository first.
